[package]
name = "ignition-schema"
version = "0.1.0"
authors = ["James Forcier <james.forcier@coreos.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
schemafy = "0.4.4"
